[package]
name = "quad-tween"
version = "0.1.0"
authors = ["xLin <xLinAbsL@outlook.com>"]
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
macroquad = "0.4.0"